//
// Warning:
// This file is generated by go compiler, don't change it!!!
// Generated Time: "2022-03-21 19:54:58"
//
package typex

type Version struct {
	Version   string
	ReleaseTime string
}

var DefaultVersion = Version{
	Version:   `V0.1.0-dd11a6f6afa5af7`,
	ReleaseTime: "2022-03-21 19:54:58",
}

